### ISSUE TITLE
Using TCA Refactor on relative abundance data

### ISSUE THREAD

**Issue by LeahBriscoe** [cran/TCA#1]
Refactor shows SVD error when used on relative abundance matrix, even when low variance features are removed (any feature with variance < 1e-4). 

df = matrix where each sample column sums to 1 (any features with constant values or less than 5 samples non zero are removed)
num_factors = 10 (or anywhere from 1 to 20 also errors out)

`refactor_res = refactor(input_abundance_table, k=num_factors)
`

Error:
`Loading required package: TCA
INFO [2020-04-27 12:59:44] Starting refactor...
INFO [2020-04-27 12:59:44] Running PCA on X using rand_svd == FALSE...
Error in La.svd(x, nu = 0) : a dimension is zero
Calls: refactor -> refactor.run -> fast.prcomp -> La.svd`

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Thanks!
